### ISSUE TITLE
Empty file causes invalid array read.

### ISSUE THREAD

**Issue by Danack** [theseer/tokenizer#1]
Hi,

I've been using this library though the infection mutation test suite.

Analyzing our client's code blew up with the error:

```
PHP Notice:  Undefined offset: 0 in
         /projects/scredible/aitekz/AitekzServer/vendor/theseer/tokenizer/src/Tokenizer.php on line 47
         PHP Stack trace:
```

It seems to be caused by this lin:
https://github.com/theseer/tokenizer/blob/cb2f008f3f05af2893a87208fe6a6c4985483f8b/src/Tokenizer.php#L46

It could be prevented by just checking that the returned array isn't empty before that.

**Comment by equinoxmatt** [comment]
Can confirm I also came across this today. It is a stupid cause (empty files), but it still should be addressed.

**Comment by theseer** [comment]
Sorry for the radio silence. 
Somehow I must have managed to unwatch my own repository and didn't get this notification.

I'll fix that asap ;)

**Comment by theseer** [comment]
I changed the code to return an empty `TokenCollection` when an empty string is passed.

One might argue though, it's pointless to even run the `Tokenizer` in such a case and an exception should be thrown instead. Given that PHP doesn't care if `token_get_all()` gets called with an empty string and consequently just returns an empty array the empty `TokenCollection` could be considered consistent behavior.

So, empty collection it is.
