### ISSUE TITLE
Adopt, if needed, to PHP 8's T_NAME_FULLY_QUALIFIED, T_NAME_RELATIVE, and T_NAME_QUALIFIED tokens

### ISSUE THREAD

**Issue by sebastianbergmann** [theseer/tokenizer#12]
* https://wiki.php.net/rfc/namespaced_names_as_token
* https://github.com/php/php-src/pull/5827

**Comment by theseer** [comment]
Given those are official Tokens, the [`\token_name()`](https://github.com/theseer/tokenizer/blob/master/src/Tokenizer.php#L76) call should translate them just fine - shouldn't it?

What would we need to change here?

**Comment by sebastianbergmann** [comment]
I do not know if there is anything that has to be done here. Unlike php-token-stream, this library does not have individual, custom classes for each token. I just wanted to make sure you were aware of this change. Feel free to close this issue if no changes are required.

**Comment by theseer** [comment]
To make it "work", no changes are required. The code should work just fine, it will just see additional, previously unknown, tokens. Given those are actual Tokens and not those [censored] string-pseudo-tokens, the `Tokenizer` won't even notice.

When PHP 8 is used, the XML representation of will differ from the the XML representation generated with PHP 7.x - for probably obvious reasons. Question is: Is that something we should address?
